import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'project',
  title: 'Projects / المشاريع',
  type: 'document',
  fields: [
    defineField({ name: 'titleAr', title: 'Title (Arabic)', type: 'string', validation: (R) => R.required() }),
    defineField({ name: 'titleFr', title: 'Title (French)', type: 'string' }),
    defineField({ name: 'titleEn', title: 'Title (English)', type: 'string', validation: (R) => R.required() }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'titleEn', maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({ name: 'descriptionAr', title: 'Short Description (Arabic)', type: 'text', rows: 3 }),
    defineField({ name: 'descriptionFr', title: 'Short Description (French)', type: 'text', rows: 3 }),
    defineField({ name: 'descriptionEn', title: 'Short Description (English)', type: 'text', rows: 3 }),
    defineField({ name: 'longDescriptionAr', title: 'Long Description (Arabic)', type: 'array', of: [{ type: 'block' }] }),
    defineField({ name: 'longDescriptionFr', title: 'Long Description (French)', type: 'array', of: [{ type: 'block' }] }),
    defineField({ name: 'longDescriptionEn', title: 'Long Description (English)', type: 'array', of: [{ type: 'block' }] }),
    defineField({
      name: 'mainImage',
      title: 'Main Image (Card Cover)',
      type: 'image',
      options: { hotspot: true },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'images',
      title: 'Gallery Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'technologies',
      title: 'Technologies Used / التقنيات المستخدمة',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          // Languages
          { title: 'HTML5', value: 'HTML' },
          { title: 'CSS3', value: 'CSS' },
          { title: 'JavaScript', value: 'JavaScript' },
          { title: 'TypeScript', value: 'TypeScript' },
          { title: 'PHP', value: 'PHP' },
          { title: 'Python', value: 'Python' },
          { title: 'Java', value: 'Java' },
          { title: 'C#', value: 'C#' },
          { title: 'Swift', value: 'Swift' },
          { title: 'Kotlin', value: 'Kotlin' },
          { title: 'Dart', value: 'Dart' },

          // Frameworks / Libraries
          { title: 'React', value: 'React' },
          { title: 'Next.js', value: 'Next.js' },
          { title: 'Vue.js', value: 'Vue.js' },
          { title: 'Angular', value: 'Angular' },
          { title: 'Node.js', value: 'Node.js' },
          { title: 'Express', value: 'Express' },
          { title: 'Laravel', value: 'Laravel' },
          { title: 'Django', value: 'Django' },
          { title: 'Spring Boot', value: 'Spring Boot' },
          { title: 'Flutter', value: 'Flutter' },
          { title: 'React Native', value: 'React Native' },
          { title: 'Tailwind CSS', value: 'Tailwind CSS' },
          { title: 'Bootstrap', value: 'Bootstrap' },

          // Databases
          { title: 'MySQL', value: 'MySQL' },
          { title: 'PostgreSQL', value: 'PostgreSQL' },
          { title: 'MongoDB', value: 'MongoDB' },
          { title: 'Firebase', value: 'Firebase' },
          { title: 'Supabase', value: 'Supabase' },
          { title: 'Redis', value: 'Redis' },

          // CMS & E-commerce
          { title: 'Sanity', value: 'Sanity' },
          { title: 'WordPress', value: 'WordPress' },
          { title: 'Shopify', value: 'Shopify' },
          { title: 'WooCommerce', value: 'WooCommerce' },
          { title: 'Strapi', value: 'Strapi' },

          // Tools & Control Panels
          { title: 'cPanel', value: 'cPanel' },
          { title: 'Plesk', value: 'Plesk' },
          { title: 'CyberPanel', value: 'CyberPanel' },
          { title: 'HestiaCP', value: 'HestiaCP' },
          { title: 'DirectAdmin', value: 'DirectAdmin' },
          { title: 'Docker', value: 'Docker' },
          { title: 'NGINX', value: 'NGINX' },
          { title: 'Apache', value: 'Apache' },
          { title: 'Vercel', value: 'Vercel' },
          { title: 'Netlify', value: 'Netlify' },
          { title: 'AWS', value: 'AWS' },
          { title: 'DigitalOcean', value: 'DigitalOcean' },
        ],
        layout: 'grid',
      },
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Website', value: 'website' },
          { title: 'Web App', value: 'webapp' },
          { title: 'Mobile App', value: 'mobile' },
          { title: 'Online Store', value: 'ecommerce' },
          { title: 'Other', value: 'other' },
        ],
      },
    }),
    defineField({ name: 'liveUrl', title: 'Live URL', type: 'url' }),
    defineField({ name: 'githubUrl', title: 'GitHub URL', type: 'url' }),
    defineField({ name: 'client', title: 'Client Name', type: 'string' }),
    defineField({ name: 'year', title: 'Year', type: 'string' }),
    defineField({ name: 'featured', title: 'Featured on Homepage', type: 'boolean', initialValue: false }),
    defineField({
      name: 'displayMode',
      title: 'Gallery Display Mode',
      type: 'string',
      options: {
        list: [
          { title: 'Grid (Premium Grid)', value: 'grid' },
          { title: 'Carousel (Scroll Snap)', value: 'snap' },
          { title: 'Masonry (Mixed Heights)', value: 'masonry' },
          { title: 'Stacked (Overlapping)', value: 'stacked' },
          { title: 'Full Slider (Single)', value: 'slider' },
          { title: 'Vertical Column', value: 'list' },
        ],
      },
      initialValue: 'snap',
    }),
    defineField({
      name: 'animationType',
      title: 'Entrance Animation',
      type: 'string',
      options: {
        list: [
          { title: 'Fade In', value: 'fade' },
          { title: 'Slide Up', value: 'slideUp' },
          { title: 'Slide Down', value: 'slideDown' },
          { title: 'Slide Left', value: 'slideLeft' },
          { title: 'Slide Right', value: 'slideRight' },
          { title: 'Zoom In', value: 'zoom' },
          { title: 'Zoom Out', value: 'zoomOut' },
          { title: 'Skew In', value: 'skew' },
          { title: 'Rotate In', value: 'rotate' },
          { title: 'Flip In', value: 'flip' },
          { title: 'Bounce In', value: 'bounce' },
          { title: 'Blur In', value: 'blur' },
        ],
      },
      initialValue: 'slideUp',
    }),
    defineField({ name: 'orderRank', title: 'Order Rank', type: 'number' }),
  ],
  orderings: [
    { title: 'Manual Order', name: 'orderRank', by: [{ field: 'orderRank', direction: 'asc' }] },
    { title: 'Year (Newest)', name: 'yearDesc', by: [{ field: 'year', direction: 'desc' }] },
  ],
  preview: {
    select: { title: 'titleEn', media: 'mainImage', subtitle: 'category' },
    prepare({ title, media, subtitle }) {
      return {
        title: title || 'مشروع جديد (بدون عنوان)',
        media,
        subtitle,
      };
    },
  },
});
